# Site settings
title: My random thoughts
email: hajyoussef.amine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Amine Hajyoussef blog  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: aminehajyoussef
github_username: pindexis 

# Build settings
markdown: kramdown
